pipeline {
    agent any

    tools {
        maven 'Maven'   // Name of Maven installation configured in Jenkins Global Tool Config
        jdk 'Jdk17'  
    }

    environment {
        GIT_REPO_URL = 'https://github.com/arshathahamed10-pixel/ai_workspace.git'
        GIT_BRANCH   = 'dev'
        APP_DIR      = 'spring-boot-app'
        DC_CHECK     = 'C:\\Program Files\\dependency-check'
        PATH = "C:\\Program Files\\grype_0.116.0_windows_amd64;${env.PATH}"
        NVD_API_KEY = credentials('NVDAPI')
        NVD_DATA_DIR = '/var/jenkins_data/dependency-check-db'
    }

    stages {

        // stage('Checkout') {
        //     steps {
        //         git branch: "${GIT_BRANCH}",
        //             url: "${GIT_REPO_URL}",
        //             credentialsId: 'ARSHATH10'   // Jenkins credential ID for git access
        //     }
        // }

         stage('Build') {
            steps {
                dir("${APP_DIR}") {
                    bat 'mvn clean package -DskipTests'
                }
            }
        }

        // stage('Verify Grype Installed') {
        //     steps {
        //         bat 'grype version'
        //     }
        // }

        //   stage('Grype Vulnerability Scan') {
        //     steps {
        //         dir("${APP_DIR}") {
        //             bat 'grype db update'
        //             bat 'grype dir:. -o json --file grype-report.json'
        //             bat 'grype dir:. -o table'
        //         }
        //     }
        // }

         stage('OWASP Dependency-Check') {
            steps {
                dependencyCheck additionalArguments: '''
                    -o "./"
                    -s "./"
                    -f "ALL"
                    --prettyPrint
                    --nvdApiKey ${NVD_API_KEY}
                    --data  ${NVD_DATA_DIR}
                    --noupdate
                ''', odcInstallation: 'CVC scanner'
            }
        }

        stage('Zip Report') {
            steps {
                dir("${APP_DIR}") {
                    powershell """
                        Compress-Archive -Path dependency-check-report.* -DestinationPath dependency-check-report-${env.BUILD_NUMBER}.zip -Force
                    """
                }
            }
        }
        stage('Archive Report') {
            steps {
                archiveArtifacts artifacts: "${APP_DIR}/dependency-check-report-${env.BUILD_NUMBER}.zip",
                                  allowEmptyArchive: false,
                                  fingerprint: true
            }
        }
        stage('Publish Report') {
            steps {
                dependencyCheckPublisher pattern: "${APP_DIR}/dependency-check-report.xml"
            }
        }

        // stage('Publish Report') {
        //     steps {
        //         dependencyCheckPublisher pattern: 'dependency-check-report.xml'
        //     }
        // }
        
    }

    post {
        success {
            echo 'Build completed successfully!'
        }
        failure {
            echo 'Build failed!'
        }
    }
}
