pipeline {
    agent any

    tools {
        maven 'Maven'   // Name of Maven installation configured in Jenkins Global Tool Config
        jdk 'Jdk17'      // Name of JDK installation configured in Jenkins Global Tool Config
    }

    environment {
        GIT_REPO_URL = 'https://github.com/arshathahamed10-pixel/ai_workspace.git'
        GIT_BRANCH   = 'dev'
        APP_DIR      = 'spring-boot-app'
    }

    stages {

        stage('Checkout') {
            steps {
                git branch: "${GIT_BRANCH}",
                    url: "${GIT_REPO_URL}",
                    credentialsId: 'ARSHATH10'   // Jenkins credential ID for git access
            }
        }

         stage('Build') {
            steps {
                dir("${APP_DIR}") {
                    bat 'mvn clean package -DskipTests'
                }
            }
        }

         stage('Grype Vulnerability Scan') {
            steps {
                dir("${APP_DIR}") {
                    bat 'grype db update'
                    bat 'grype dir:. -o json > grype-report.json'
                }
            }
        }
        
    }

    post {
        success {
            echo 'Build completed successfully!'
        }
        failure {
            echo 'Build failed!'
        }
    }
}
